name: Codecov Coverage

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  codecov:
    name: Run Codecov
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Build and run tests
        run: |
          mvn clean verify

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
