# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# Author: Cesar Perez
# Event: "Semana de Impacto BCP - 2024"

name: Deploy API Rest to Azure Web App - employer-api-rest

on:
  push:
    branches: [ master ]

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Compile with Maven
        run: mvn compile

  test:
    runs-on: ubuntu-latest
    needs: compile

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Test with Maven
        run: mvn test

      - name: Generate Jacoco coverage report
        run: mvn jacoco:report

#      - name: Upload coverage reports to Codecov
#        # uses: codecov/codecov-action@v4.0.1
#        uses: codecov/codecov-action@v4
#        env:
#          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload coverage CodeCov
        if: success()
        run: |
          curl -s https://codecov.io/bash | bash
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        shell: bash

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn -B package --file pom.xml -Dmaven.test.skip=true

#      - name: generate report codecov
#        run: mvn cobertura:cobertura
#      - name: Upload coverage
#        if: success()
#        run: |
#          curl -s https://codecov.io/bash | bash
#        env:
#          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
#        shell: bash

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
  
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: java-app
      
#      - name: Login to Azure
#        uses: azure/login@v1
#        with:
#          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
#          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
#          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'employer-api-rest'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          slot-name: 'Production'
          package: '*.jar'
          